/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:6cf5baf3-29fc-409e-a432-ed0fc217fa82",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ddUbJ1drM",
    "aws_user_pools_web_client_id": "6spgtvcmpnu5i9rnqpc375l3ki",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "2bookmarkclient-20230420161656-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://2bookmarkclient-20230420161656-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
